### ISSUE TITLE
一个关于ReaderResult功能请求

### ISSUE THREAD

**Issue by ydq** [biezhi/excel-plus#12]
针对 **ReaderResult** 的处理，我有个想法。

因为 目前 **excel-plus** 的 **ReaderResult** 没有提供直接获取 **List<Pair<Integer, T>> result** 或者直接对 **result** 进行操作的方法（为啥不直接暴露内部的result对象呢？）

导致result的 Excel 行号在执行类似于 **asList()** 方法之后会丢失行号信息，只剩下单纯的对象列表了

所以ReaderResult是否可以直提供result的获取方法，或者提供针对result集合的“流式”的操作（如filter、peek等，目前只有valid）

比如我目前手头有个需求就对于成功的结果是必须要明确获取到对应Excel中的行号信息，对于失败的结果也要求行号和原始数据的回传，而现在只能在valid方法上进行扩展，在这里将行号回填，如果有错误信息将错误信息封装到自己的bean，并且错误的信息也要返回成validRow.ok()才能获取到完整的处理好的数据，然后自己根据最终获取到的集合重新用个流来进行错误和正确的分组。

**Comment by biezhi** [comment]
在 https://github.com/biezhi/excel-plus/commit/c5157f3268cb07958aeba98024371638c44bfeac 提交中已实现，[示例代码](https://github.com/biezhi/excel-plus/blob/dev/src/test/java/io/github/biezhi/excel/plus/examples/ReaderExample.java#L101)
