### ISSUE TITLE
导出2000条row的时候效率很低

### ISSUE THREAD

**Issue by RoyXiBoy** [biezhi/excel-plus#15]
群主大大，上周使用excelplus写入2000条数据，越到后面越慢，大概花了半个小时，看了一下花销，主要都花销在writeRows里面autoSizeColumn这个方法里。

原因应该和这个url里面说的一样
http://www.beyond-free.com/post/2016-07-01_be-careful-about-poi-autosizecolumn

**Comment by jhsea3do** [comment]
https://github.com/biezhi/excel-plus/blob/c065d137f718a7d6f5f0533734639cfca098e438/src/main/java/io/github/biezhi/excel/plus/writer/ExcelWriter.java#L203

我也遇到了 ，我的做法是挪到while 外面

**Comment by biezhi** [comment]
@RoyXiBoy 我最近在重构这部分代码，100w 行数据读取和写入的测试在 30s 左右。
该版本尚未发布，还有一些其他测试在做，[测试代码](https://github.com/biezhi/excel-plus/blob/v1.0/src/test/java/io/github/biezhi/excel/plus/WriterTest.java#L21)

**Comment by biezhi** [comment]
该版本已发布，忘记这里的 issue 了。
