### ISSUE TITLE
[建议]希望可以在运行时动态指定 sheet 名

### ISSUE THREAD

**Issue by veir-panda** [biezhi/excel-plus#3]
## 需求

如果一个Excel表的多个Sheet除了数据以外其他都是相同的，那么我得为这多个Sheet编写几乎一样的model类，仅仅只是因为他们的Sheet名不同。

## 建议

所以我觉得可以增加一个可以动态制定sheet名的的功能，方便对同一个model重用。

**Comment by biezhi** [comment]
@veir-panda 可以在读取的时候指定 `sheet` 的索引或名称。

![图片](https://user-images.githubusercontent.com/3849072/56719084-9b3e6100-6772-11e9-9499-919900d3e731.png)
