### ISSUE TITLE
问题：在解析excel时，一行记录如果前一格数据为空，那获取到的数据将是后一格数据就会往前移动一格

### ISSUE THREAD

**Issue by yangkebiao** [biezhi/excel-plus#6]
![12312312](https://user-images.githubusercontent.com/17536440/43310190-7ce0072a-91b9-11e8-8db4-23cef01fe4b7.png)
比如此图中银行卡为空，后面金额为100，那获取出来的对象里面银行卡数值为100

**Comment by ydq** [comment]
我也碰到了相同的问题，excel2007 xlsx格式，使用SAX方式解析会出现此问题，使用DOM解析则可以正确解析。
